### ISSUE TITLE
Please update the version on PyPI

### ISSUE THREAD

**Issue by clausecker** [nwg-piotr/autotiling#52]
I am the maintainer of the FreeBSD port of this package.

On FreeBSD, we prefer to draw Python packages from PyPI.  Unfortunately, the autotiling package is still on 1.8 over there.  Please check if you can upload the newest version of the package to PyPI.

**Comment by nwg-piotr** [comment]
It happened due to the version mismatch, my bad. The PyPI workflow has been [contributed](https://github.com/nwg-piotr/autotiling/pull/39) in 2022, and it just worked so far. Should be fixed now.

**Comment by tastytea** [comment]
it seems there is still a problem, it is still on 1.9.1 [on PyPi](https://pypi.org/project/autotiling/)

**Comment by nwg-piotr** [comment]
Not really. It reported [the error](https://github.com/nwg-piotr/autotiling/actions/runs/8855174558) which I have no idea on how to fix.

**Comment by Syphdias** [comment]
Have you tried `actions/checkout@v4` and `actions/setup-python@v5`?

**Comment by Syphdias** [comment]
As far as I understand, once uploaded the files can no longer be changed. The GitHub Action allows to skip this. 
https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#tolerating-release-package-file-duplicates

I wonder where it is coming from though :thinking:

**Comment by nwg-piotr** [comment]
I would be grateful for a PR. I don't use this script in real life, and also I'm completely unfamiliar with PyPi.

**Comment by Syphdias** [comment]
Sure, I updated the action versions and added the skip option for the publish action.
